## YAML Template.
---
spring:
    application:
        name: api-gateway
    cloud:
        config:
          uri: http://localhost:8888
server:
    port: 8079

zuul:
    routes:
        orders:            
            service-id: order-service
            path: /orders/**
            stripPrefix: true
        customers:            
            service-id: customer-service
            path: /customers/**      
            stripPrefix: true
            
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka